espoo-dev/group-habits

svelte/src/App.svelte
svelte/src/lib/components/Habit.spec.ts
svelte/src/lib/components/Habit.svelte

feat: habit dinamyc component :sparkles: #14

---

backend-rails/.gitignore
backend-rails/README.md
backend-rails/config/database.yml

19 - Improve readme instructions for setup rails backend app

---

svelte/package.json
svelte/src/infra/http/AxiosAdapter.spec.ts
svelte/src/infra/http/AxiosAdapter.ts
svelte/src/infra/http/http.ts
svelte/yarn.lock

✨feat: add http service with adapter pattern #17

---

android-client/.idea/compiler.xml
android-client/.idea/gradle.xml
android-client/.idea/inspectionProfiles/Project_Default.xml
android-client/.idea/misc.xml
android-client/app/build.gradle
android-client/build.gradle
android-client/config/detekt/detekt.gradle
android-client/config/detekt/detekt.yml

Adding detekt

---

android-client/.github/workflows/android_build.yml
android-client/.idea/misc.xml

Adding github actions

---

android-client/.idea/misc.xml
android-client/build.gradle
android-client/buildscripts/ktlint.gradle

Adding ktlint

---

backend-rails/app/models/habit.rb
backend-rails/db/migrate/20221112184641_create_habits.rb
backend-rails/db/schema.rb
backend-rails/spec/factories/habits.rb
backend-rails/spec/models/habit_spec.rb

It was created a model for Habit that has an attribute name.

Create model habit

---

backend-rails/app/models/daily_habit.rb
backend-rails/app/models/habit.rb
backend-rails/db/migrate/20221113202125_create_daily_habits.rb
backend-rails/db/migrate/20221115160408_add_default_value_to_daily_habit.rb
backend-rails/db/schema.rb
backend-rails/spec/factories/daily_habits.rb
backend-rails/spec/models/daily_habit_spec.rb

It was created a model for Daily Habit that has date and check as attributes, and it belongs to habit

Create model daily habit

---

svelte/src/App.svelte
svelte/src/lib/components/HabitList.spec.ts
svelte/src/lib/components/HabitList.svelte

feat: create habit list component :sparkles:

---

svelte/package.json

feat: specify node version to install and run project :sparkles: #37

---

svelte/src/App.svelte
svelte/src/lib/components/Day/Day.spec.ts
svelte/src/lib/components/Day/Day.svelte

✨ Create day component :sparkles: #40

---

backend-rails/Gemfile
backend-rails/Gemfile.lock
backend-rails/config/initializers/apitome.rb
backend-rails/doc/api.md
backend-rails/doc/api/index.json
backend-rails/doc/api/passwords/bad.json
backend-rails/doc/api/passwords/ok.json
backend-rails/doc/api/sessions/bad.json
backend-rails/doc/api/sessions/ok.json
backend-rails/doc/api/settings/bad.json
backend-rails/doc/api/settings/ok.json
backend-rails/doc/api/status/ok.json
backend-rails/doc/api/users/bad.json
backend-rails/doc/api/users/ok.json
backend-rails/spec/spec_helper.rb

28 - Generate apidoc for rails backend

---

backend-rails/app/models/habit.rb
backend-rails/db/migrate/20221119193941_add_icon_to_habits.rb
backend-rails/db/schema.rb
backend-rails/spec/factories/habits.rb
backend-rails/spec/models/habit_spec.rb

43 - add field icon to habit

---

backend-rails/Gemfile
backend-rails/app/models/daily_habit.rb
backend-rails/app/models/user.rb
backend-rails/config/initializers/apitome.rb
backend-rails/db/migrate/20221120152037_add_daily_habits_to_user.rb
backend-rails/db/schema.rb
backend-rails/spec/factories/daily_habits.rb
backend-rails/spec/models/daily_habit_spec.rb
backend-rails/spec/models/user_spec.rb

50 - create relationship between user and daily_habits

---

backend-rails/.rubocop.yml
backend-rails/app/models/habit.rb
backend-rails/app/models/user.rb
backend-rails/spec/models/habit_spec.rb
backend-rails/spec/models/user_spec.rb
backend-rails/spec/spec_helper.rb

52 - fix rubocop issues

---

backend-rails/app/models/daily_habit.rb
backend-rails/app/models/group.rb
backend-rails/app/models/habit.rb
backend-rails/app/models/user.rb
backend-rails/db/migrate/20221121160228_add_daily_habits_to_group.rb
backend-rails/db/migrate/20221121161211_add_users_to_group.rb
backend-rails/db/migrate/20221121163813_add_habits_to_group.rb
backend-rails/db/schema.rb
backend-rails/spec/factories/daily_habits.rb
backend-rails/spec/factories/habits.rb
backend-rails/spec/factories/users.rb
backend-rails/spec/models/daily_habit_spec.rb
backend-rails/spec/models/group_spec.rb
backend-rails/spec/models/habit_spec.rb
backend-rails/spec/models/user_spec.rb

56 - Add relationships to group class

---

fake-json-server/db.json
fake-json-server/middleware.js
fake-json-server/readme.md

64 - mock backend api for sign method

---

.github/workflows/backend_rails.yml

73 - setup ci for backend_rails

---

backend-rails/app/models/daily_habit.rb
backend-rails/spec/factories/daily_habits.rb
backend-rails/spec/factories/habits.rb
backend-rails/spec/models/daily_habit_spec.rb

60 - Create scop for today daily habits

---

backend-rails/app/presenters/daily_habit_presenter.rb
backend-rails/spec/presenters/daily_habit_presenter_spec.rb

62 - create presenter for daily_habit

---

backend-rails/app/controllers/api/v1/daily_habits_controller.rb
backend-rails/app/policies/daily_habit_policy.rb
backend-rails/app/presenters/daily_habit_presenter.rb
backend-rails/config/routes.rb
backend-rails/spec/helpers.rb
backend-rails/spec/presenters/daily_habit_presenter_spec.rb
backend-rails/spec/requests/api/v1/daily_habits_request_spec.rb

59 - Create endpoint to return daily habits

---

backend-rails/app/controllers/api/v1/daily_habits_controller.rb
backend-rails/app/models/group.rb
backend-rails/spec/models/group_spec.rb
backend-rails/spec/requests/api/v1/daily_habits_request_spec.rb

80 - generate missing daily_habits

---

backend-rails/app/controllers/api/v1/daily_habits_controller.rb
backend-rails/app/services/daily_habits_finder_service.rb

82- create DailyHabitsFinderService

---

backend-rails/app/controllers/api/v1/daily_habits_controller.rb
backend-rails/app/models/daily_habit.rb
backend-rails/app/models/group.rb
backend-rails/app/policies/daily_habit_policy.rb
backend-rails/app/services/daily_habit_creator_service.rb
backend-rails/config/routes.rb
backend-rails/spec/requests/api/v1/daily_habits_request_spec.rb

49- Create daily_habit endpoint

---

node/src/domain/entity/Group.ts
node/test/Group.spec.ts
node/test/Habit.spec.ts

create group and correct one let in Habit test

---

backend-rails/app/models/category.rb
backend-rails/app/models/user.rb
backend-rails/db/migrate/20230111230929_create_category.rb
backend-rails/db/schema.rb
backend-rails/spec/factories/categories.rb
backend-rails/spec/models/category_spec.rb
backend-rails/spec/models/user_spec.rb

97 - Add Category model

---

backend-rails/app/controllers/api/v1/categories_controller.rb
backend-rails/app/policies/category_policy.rb
backend-rails/app/presenters/category_presenter.rb
backend-rails/app/services/categories_finder_service.rb
backend-rails/config/routes.rb
backend-rails/db/seeds.rb
backend-rails/spec/policies/category_policy_spec.rb
backend-rails/spec/presenters/category_presenter_spec.rb
backend-rails/spec/requests/api/v1/categories_request_spec.rb
backend-rails/spec/services/categories_finder_service_spec.rb

102 - create endpoint to list categories

---

backend-rails/app/controllers/api/v1/sessions_controller.rb
backend-rails/app/models/user.rb
backend-rails/spec/requests/api/v1/sessions/create_spec.rb

105: add token to user body

---

backend-rails/README.md
backend-rails/app/controllers/api/v1/categories_controller.rb
backend-rails/app/controllers/api/v1/daily_habits_controller.rb
backend-rails/app/presenters/base_presenter.rb
backend-rails/app/presenters/category_presenter.rb
backend-rails/app/presenters/daily_habit_presenter.rb
backend-rails/docker-compose.yml
backend-rails/spec/presenters/base_presenter_spec.rb
backend-rails/spec/presenters/category_presenter_spec.rb

107: extract logic from controllers to presenters

---

backend-rails/.rubocop.yml
backend-rails/app/controllers/api/v1/categories_controller.rb
backend-rails/app/policies/application_policy.rb
backend-rails/app/policies/category_policy.rb
backend-rails/app/services/category_creator_service.rb
backend-rails/config/routes.rb
backend-rails/spec/policies/category_policy_spec.rb
backend-rails/spec/requests/api/v1/categories_request_spec.rb
backend-rails/spec/services/category_creator_service_spec.rb

110 create endpoint to update category

---

backend-rails/app/controllers/api/v1/categories_controller.rb
backend-rails/app/policies/category_policy.rb
backend-rails/app/services/category_destroyer_service.rb
backend-rails/config/routes.rb
backend-rails/spec/policies/category_policy_spec.rb
backend-rails/spec/requests/api/v1/categories_request_spec.rb
backend-rails/spec/services/category_destroyer_service_spec.rb

112 create request to delete memory

---

backend-rails/app/controllers/api/v1/categories_controller.rb
backend-rails/app/models/category.rb
backend-rails/app/services/categories_finder_service.rb
backend-rails/spec/models/category_spec.rb
backend-rails/spec/requests/api/v1/categories_request_spec.rb
backend-rails/spec/services/categories_finder_service_spec.rb

121 filter category by name like

---

backend-rails/.rubocop.yml
backend-rails/app/services/base_service.rb
backend-rails/app/services/categories_finder_service.rb
backend-rails/app/services/category_creator_service.rb
backend-rails/app/services/category_destroyer_service.rb
backend-rails/app/services/category_updater_service.rb

124: add base service

---

backend-rails/.rubocop.yml
backend-rails/app/controllers/api/v1/items_controller.rb
backend-rails/app/models/category.rb
backend-rails/app/models/item.rb
backend-rails/app/models/user.rb
backend-rails/app/policies/item_policy.rb
backend-rails/app/presenters/item_presenter.rb
backend-rails/app/services/items_finder_service.rb
backend-rails/config/routes.rb
backend-rails/db/migrate/20230123133317_create_item.rb
backend-rails/db/schema.rb
backend-rails/spec/factories/items.rb
backend-rails/spec/models/category_spec.rb
backend-rails/spec/models/item_spec.rb
backend-rails/spec/models/user_spec.rb
backend-rails/spec/policies/item_policy_spec.rb
backend-rails/spec/presenters/item_presenter_spec.rb
backend-rails/spec/requests/api/v1/items_request_spec.rb
backend-rails/spec/services/items_finder_service_spec.rb

128 create item model

---

backend-rails/app/controllers/api/v1/items_controller.rb
backend-rails/app/models/item.rb
backend-rails/app/services/items_finder_service.rb
backend-rails/db/seeds.rb
backend-rails/spec/models/item_spec.rb
backend-rails/spec/requests/api/v1/items_request_spec.rb
backend-rails/spec/services/items_finder_service_spec.rb

130 filter items by item type

---

svelte/package.json
svelte/src/App.svelte
svelte/src/infra/http/AxiosAdapter.ts
svelte/src/lib/components/Menu/Menu.spec.ts
svelte/src/lib/components/Menu/Menu.svelte
svelte/src/main.ts
svelte/src/routes/pages/Categories.svelte
svelte/src/routes/pages/Login.svelte
svelte/yarn.lock

Add routes with Login and Categories page

---

.github/workflows/backend_rails.yml
backend-rails/.github/workflows/ci.yml
backend-rails/.rubocop.yml
backend-rails/app/models/customer.rb
backend-rails/config/locales/en.yml
backend-rails/db/migrate/20230124204835_create_customer.rb
backend-rails/db/schema.rb
backend-rails/spec/factories/customers.rb
backend-rails/spec/models/customer_spec.rb

137 create customer model

---

backend-rails/app/controllers/api/v1/customers_controller.rb
backend-rails/app/models/customer.rb
backend-rails/app/models/user.rb
backend-rails/app/policies/customer_policy.rb
backend-rails/app/presenters/customer_presenter.rb
backend-rails/app/services/customers_finder_service.rb
backend-rails/config/routes.rb
backend-rails/spec/factories/customers.rb
backend-rails/spec/models/customer_spec.rb
backend-rails/spec/models/user_spec.rb
backend-rails/spec/policies/customer_policy_spec.rb
backend-rails/spec/presenters/customer_presenter_spec.rb
backend-rails/spec/requests/api/v1/customers_request_spec.rb
backend-rails/spec/services/customers_finder_service_spec.rb

140 create endpoint to list categories

---

backend-rails/app/controllers/api/v1/api_controller.rb
backend-rails/app/controllers/api/v1/categories_controller.rb
backend-rails/app/controllers/api/v1/customers_controller.rb
backend-rails/app/controllers/api/v1/daily_habits_controller.rb
backend-rails/app/controllers/api/v1/items_controller.rb
backend-rails/app/controllers/api/v1/settings_controller.rb
backend-rails/app/controllers/application_controller.rb
backend-rails/db/seeds.rb

143: remove unused pundit verifications

---

backend-rails/app/policies/category_policy.rb
backend-rails/app/policies/customer_policy.rb
backend-rails/app/policies/daily_habit_policy.rb
backend-rails/app/policies/item_policy.rb

141: refactor policies::scope

---

backend-rails/app/models/category.rb
backend-rails/app/models/concerns/name_filterable.rb
backend-rails/app/models/customer.rb
backend-rails/app/models/item.rb
backend-rails/spec/models/category_spec.rb

144: ignore case for filter by_name_like

---

backend-rails/app/controllers/api/v1/customers_controller.rb
backend-rails/app/services/customer_updater_service.rb
backend-rails/config/routes.rb
backend-rails/spec/requests/api/v1/customers_request_spec.rb
backend-rails/spec/services/customer_updater_service_spec.rb

154 create endpoint to update customers

---

backend-rails/app/controllers/api/v1/api_controller.rb
backend-rails/app/controllers/api/v1/categories_controller.rb
backend-rails/app/controllers/api/v1/customers_controller.rb
backend-rails/app/services/category_destroyer_service.rb
backend-rails/app/services/customer_destroyer_service.rb
backend-rails/config/routes.rb
backend-rails/spec/requests/api/v1/customers_request_spec.rb
backend-rails/spec/services/category_destroyer_service_spec.rb
backend-rails/spec/services/customer_destroyer_service_spec.rb

168 create destroy customer endpoint

---

svelte/src/data/usecases/remote-categories.ts
svelte/src/infra/http/index.ts
svelte/src/infra/http/response-handler.ts
svelte/src/main/factories/usecases/remote-category-factory.ts
svelte/src/test/infra/http/response-handler.spec.ts

🔨 Add response handler and refactor list to use response handler

---

backend-rails/app/models/customer.rb
backend-rails/spec/models/customer_spec.rb
backend-rails/spec/requests/api/v1/customers_request_spec.rb

184: validate presence for customer type

---

svelte/src/lib/components/Modal/Modal.spec.ts
svelte/src/lib/components/Modal/Modal.svelte

feat: create modal component :sparkles: #195

---

svelte/index.html
svelte/src/data/protocols/http/http-client.ts
svelte/src/data/usecases/remote-categories.ts
svelte/src/domain/usecases/categories.ts
svelte/src/infra/http/response-handler.ts
svelte/src/routes/pages/Categories.svelte
svelte/src/test/infra/http/response-handler.spec.ts

feat: add new category #197

---

backend-rails/app/models/unit_type.rb
backend-rails/db/migrate/20230203173032_create_unit_type.rb
backend-rails/db/schema.rb
backend-rails/spec/factories/items.rb
backend-rails/spec/factories/unit_types.rb
backend-rails/spec/models/item_spec.rb
backend-rails/spec/models/unit_type_spec.rb

189: extract unit type to an entity

---

backend-rails/app/models/sales_unit.rb
backend-rails/db/migrate/20230203175331_rename_unit_type_to_sales_unit.rb
backend-rails/db/schema.rb
backend-rails/spec/factories/sales_unit.rb
backend-rails/spec/models/sales_unit_spec.rb

204: rename unit_type to sales_unit

---

backend-rails/app/models/item.rb
backend-rails/app/models/sales_unit.rb
backend-rails/app/presenters/item_presenter.rb
backend-rails/db/migrate/20230206184651_remove_sales_unit_from_item.rb
backend-rails/db/migrate/20230206185305_add_sales_unit_to_item.rb
backend-rails/db/schema.rb
backend-rails/db/seeds.rb
backend-rails/spec/factories/items.rb
backend-rails/spec/factories/sales_unit.rb
backend-rails/spec/models/item_spec.rb
backend-rails/spec/models/sales_unit_spec.rb
backend-rails/spec/presenters/item_presenter_spec.rb

203 replace unit type string per sales unit entity

---

svelte/src/lib/components/Popover/Popover.spec.ts
svelte/src/lib/components/Popover/Popover.svelte

✨ create popover component

---

svelte/src/data/usecases/remote-categories.ts
svelte/src/domain/usecases/categories.ts
svelte/src/routes/pages/Categories.svelte

✨  remove category #198

---

svelte/src/test/data/mocks/index.ts
svelte/src/test/data/mocks/mock-remote-categories.ts
svelte/src/test/data/usecases/remote-categories.spec.ts

216 improve api categories tests 🧪 

---

backend-rails/app/presenters/item_presenter.rb
backend-rails/app/presenters/sales_unit_presenter.rb
backend-rails/app/services/items/items_finder_service.rb
backend-rails/spec/presenters/item_presenter_spec.rb
backend-rails/spec/presenters/sales_unit_presenter_spec.rb

210 add sales unit to item presenter

---

svelte/src/infra/notification/notification.ts
svelte/src/lib/components/Toast/Toast.spec.ts
svelte/src/lib/components/Toast/Toast.svelte

Create toast service and component #222 ✨ 

---

svelte/src/App.svelte
svelte/src/routes/pages/Login.svelte

feat: using notification service when login #224 :sparkles:

---

svelte/src/data/usecases/remote-categories.ts
svelte/src/domain/usecases/categories.ts
svelte/src/routes/pages/Categories.svelte

feat: edit category data #229

---

svelte/src/lib/components/Toast/Toast.svelte
svelte/src/lib/components/Toast/ToastTemplate.svelte

art: improve toast layout :art:

---

svelte/src/infra/notification/notification.ts
svelte/src/routes/pages/Categories.svelte

feat: add error msg and set timeout default :sparkles:

---

backend-rails/app/presenters/item_presenter.rb
backend-rails/spec/requests/api/v1/items_request_spec.rb

242: change sales_price and purchase_price to float in json

---

.vscode/settings.json
svelte/src/routes/pages/Categories.svelte

feat: add missing feedback messages #249 :sparkles:

---

backend-rails/app/controllers/api/v1/items_controller.rb
backend-rails/app/services/items/item_creator_service.rb
backend-rails/config/routes.rb
backend-rails/spec/requests/api/v1/items_request_spec.rb
backend-rails/spec/services/items/item_creator_service_spec.rb

255 add endpoint to create item

---

svelte/src/data/usecases/remote-customers.ts
svelte/src/domain/models/customer-model.ts
svelte/src/domain/usecases/customers.ts
svelte/src/domain/usecases/index.ts
svelte/src/main/factories/usecases/remote-customer-factory.ts
svelte/src/test/data/mocks/mock-remote-customers.ts
svelte/src/test/data/usecases/remote-customers.spec.ts

feat: add customer services and factory :sparkles: #263

---

backend-rails/app/controllers/api/v1/items_controller.rb
backend-rails/app/services/items/item_destroyer_service.rb
backend-rails/config/routes.rb
backend-rails/spec/requests/api/v1/items_request_spec.rb
backend-rails/spec/services/items/item_destroyer_service_spec.rb

267 create endpoint to delete item

---

svelte/.env
svelte/src/main/factories/usecases/remote-authentication-factory.ts
svelte/src/main/factories/usecases/remote-category-factory.ts
svelte/src/main/factories/usecases/remote-customer-factory.ts
svelte/vite.config.js

feat: add enviroments config to base url

---

backend-rails/app/controllers/api/v1/items_controller.rb
backend-rails/app/services/items/item_updater_service.rb
backend-rails/config/routes.rb
backend-rails/spec/requests/api/v1/items_request_spec.rb
backend-rails/spec/services/items/item_updater_service_spec.rb

269: add update items endpoint

---

backend-rails/app/controllers/api/v1/categories_controller.rb
backend-rails/app/controllers/api/v1/customers_controller.rb
backend-rails/app/controllers/api/v1/items_controller.rb
backend-rails/app/services/base_service.rb
backend-rails/app/services/categories/categories_finder_service.rb
backend-rails/app/services/categories/category_creator_service.rb
backend-rails/app/services/categories/category_destroyer_service.rb
backend-rails/app/services/categories/category_updater_service.rb
backend-rails/app/services/customers/customer_creator_service.rb
backend-rails/app/services/customers/customer_destroyer_service.rb
backend-rails/app/services/customers/customer_updater_service.rb
backend-rails/app/services/customers/customers_finder_service.rb
backend-rails/app/services/items/item_creator_service.rb
backend-rails/app/services/items/item_destroyer_service.rb
backend-rails/app/services/items/item_updater_service.rb
backend-rails/app/services/items/items_finder_service.rb
backend-rails/spec/services/categories/categories_finder_service_spec.rb
backend-rails/spec/services/categories/category_creator_service_spec.rb
backend-rails/spec/services/categories/category_destroyer_service_spec.rb
backend-rails/spec/services/categories/category_updater_service_spec.rb
backend-rails/spec/services/customers/customer_creator_service_spec.rb
backend-rails/spec/services/customers/customer_destroyer_service_spec.rb
backend-rails/spec/services/customers/customer_updater_service_spec.rb
backend-rails/spec/services/customers/customers_finder_service_spec.rb
backend-rails/spec/services/items/item_creator_service_spec.rb
backend-rails/spec/services/items/item_destroyer_service_spec.rb
backend-rails/spec/services/items/item_updater_service_spec.rb
backend-rails/spec/services/items/items_finder_service_spec.rb

288 refactor services and controller params

---

backend-rails/app/controllers/api/v1/sales_units_controller.rb
backend-rails/app/policies/sales_unit_policy.rb
backend-rails/app/services/sales_units/sales_units_finder_service.rb
backend-rails/config/database.yml
backend-rails/config/routes.rb
backend-rails/spec/requests/api/v1/sales_units_request_spec.rb
backend-rails/spec/services/sales_units/sale_units_finder_service_spec.rb

211: add endpoint to list sales units

---

svelte/src/lib/components/Radio/Radio.spec.ts
svelte/src/lib/components/Radio/Radio.svelte

feat: create radio component #313

---

backend-rails/app/models/customer.rb
backend-rails/app/models/service_order.rb
backend-rails/app/models/user.rb
backend-rails/db/migrate/20230221163618_create_service_orders.rb
backend-rails/db/schema.rb
backend-rails/db/seeds.rb
backend-rails/spec/factories/service_orders.rb
backend-rails/spec/models/customer_spec.rb
backend-rails/spec/models/service_order_spec.rb
backend-rails/spec/models/user_spec.rb

318: create service order model

---

backend-rails/.rubocop.yml
backend-rails/app/controllers/api/v1/service_orders_controller.rb
backend-rails/app/models/service_order.rb
backend-rails/app/policies/service_order_policy.rb
backend-rails/app/presenters/service_order_presenter.rb
backend-rails/app/services/service_orders/service_orders_finder_service.rb
backend-rails/config/routes.rb
backend-rails/spec/policies/service_order_policy_spec.rb
backend-rails/spec/presenters/service_order_presenter_spec.rb
backend-rails/spec/requests/api/v1/service_orders_request_spec.rb
backend-rails/spec/services/service_orders/service_orders_finder_service_spec.rb

330 create endpoint to list service orders

---

backend-rails/app/controllers/api/v1/service_orders_controller.rb
backend-rails/app/services/service_orders/service_order_destroyer_service.rb
backend-rails/config/routes.rb
backend-rails/spec/requests/api/v1/service_orders_request_spec.rb
backend-rails/spec/services/service_orders/service_order_destroyer_service_spec.rb

336 create endpoint to delete service order

---

backend-rails/app/controllers/api/v1/service_orders_controller.rb
backend-rails/app/services/service_orders/service_order_creator_service.rb
backend-rails/config/routes.rb
backend-rails/spec/requests/api/v1/service_orders_request_spec.rb
backend-rails/spec/services/service_orders/service_order_creator_service_spec.rb

342 add endpoint to create service order

---

svelte/src/data/usecases/remote-items.ts
svelte/src/domain/models/item-model.ts
svelte/src/domain/usecases/index.ts
svelte/src/domain/usecases/items.ts
svelte/src/test/data/mocks/mock-remote-items.ts
svelte/src/test/data/usecases/remote-items.spec.ts

feat: create items list usecase, model and service #334 :sparkles:

---

svelte/src/lib/components/Select/Select.spec.ts
svelte/src/lib/components/Select/Select.svelte
svelte/src/routes/pages/Login.svelte

355 create select component

---

backend-rails/.rubocop.yml
backend-rails/app/lib/date_util.rb
backend-rails/app/presenters/service_order_presenter.rb
backend-rails/app/services/service_orders/service_order_creator_service.rb
backend-rails/spec/lib/date_util_spec.rb
backend-rails/spec/presenters/service_order_presenter_spec.rb
backend-rails/spec/requests/api/v1/service_orders_request_spec.rb
backend-rails/spec/services/service_orders/service_order_creator_service_spec.rb

351 for creating service order accept params creation date and conclusion date

---

backend-rails/app/controllers/api/v1/service_orders_controller.rb
backend-rails/app/services/service_orders/service_order_updater_service.rb
backend-rails/config/routes.rb
backend-rails/spec/requests/api/v1/service_orders_request_spec.rb
backend-rails/spec/services/service_orders/service_order_updater_service_spec.rb

375 add endpoint to update service order

---

backend-rails/app/controllers/api/v1/service_orders_controller.rb
backend-rails/app/models/service_order.rb
backend-rails/app/presenters/service_order_presenter.rb
backend-rails/app/services/service_orders/service_orders_finder_service.rb
backend-rails/db/migrate/20230311181913_remove_name_from_service_order.rb
backend-rails/db/schema.rb
backend-rails/db/seeds.rb
backend-rails/spec/factories/service_orders.rb
backend-rails/spec/models/service_order_spec.rb
backend-rails/spec/presenters/service_order_presenter_spec.rb
backend-rails/spec/requests/api/v1/service_orders_request_spec.rb
backend-rails/spec/services/service_orders/service_order_creator_service_spec.rb
backend-rails/spec/services/service_orders/service_order_updater_service_spec.rb
backend-rails/spec/services/service_orders/service_orders_finder_service_spec.rb

371: remove service order name
